HashMap used for fetching modulators using getModulator() in CtrlrPanel this might cause unexpected behavior and is highly experimental (should speed up all Lua calls to getComponent() and getModulatorByname())

diff --git a/Scripts/post-commit b/Scripts/post-commit
--- a/Scripts/post-commit
+++ b/Scripts/post-commit
@@ -7,6 +7,7 @@ BUILD_LOG_WIN32=""
 BUILD_LOG_WIN64=""
 OUTPUT="ctrlrorg@ctrlr.org:/home/ctrlrorg/public_html/nightly/"
 VERSION=""
+ARGS=$1
 
 echo "CTRLR pre-commit HOOK"
 
@@ -19,6 +20,7 @@ function detect_os {
 		PACKAGE=$CTRLR_ROOT/Packaging/Windows/Ctrlr-$VERSION.exe
 		BUILD_LOG_WIN32=$CTRLR_ROOT/Builds/Ctrlr-$VERSION.win32.build.log
 		BUILD_LOG_WIN64=$CTRLR_ROOT/Builds/Ctrlr-$VERSION.win64.build.log
+		CTRLR_KEY=$CTRLR_ROOT/Packaging/ctrlr.key
 		return
 	fi
 		
@@ -51,6 +53,28 @@ function build_now {
 	fi
 }
 
+function windows_msbuild {
+	if [ -x "$DOTNET/MSBuild.exe" ]; then
+		echo "CTRLR: MSBuild.exe found"
+		cd $CTRLR_ROOT/Builds
+		echo "CTRLR: Build Win32"
+		$DOTNET/MSBuild.exe $CTRLR_ROOT/Builds/Ctrlr_Release.sln /fileloggerparameters:logfile=Ctrlr-$VERSION.win32.build.log /property:Configuration=Release_Nightly /property:Platform=Win32 /maxcpucount:6
+		if [ $? -ne 0 ]; then
+			echo "CTRLR: Win32 build failed"
+			exit 1
+		fi
+		echo "CTRLR: Build x64"
+		$DOTNET/MSBuild.exe $CTRLR_ROOT/Builds/Ctrlr_Release.sln /fileloggerparameters:logfile=Ctrlr-$VERSION.win64.build.log /property:Configuration=Release_Nightly /property:Platform=x64 /maxcpucount:6
+		if [ $? -ne 0 ]; then
+			echo "CTRLR: x64 build failed"
+			exit 1
+		fi
+	else
+		echo "CTRLR: $DOTNET/MSBuild.exe does not exist"
+		exit 1
+	fi
+}
+
 function build_now_windows {
 	DOTNET="/c/Windows/Microsoft.NET/Framework/v4.0.30319"
 	NSIS="/c/Program\ Files\ \(x86\)/NSIS/makensis.exe"
@@ -64,39 +88,27 @@ function build_now_windows {
 	echo
 	sed -e "s/%REVISION%/$VERSION/g" -e "s/%REVISION_DATE%/$DATE/g" $TEMPLATE_H > $REVISION_H
 	
-	if [ -x "$DOTNET/MSBuild.exe" ]; then
-		echo "CTRLR: MSBuild.exe found"
-		cd $CTRLR_ROOT/Builds
-		echo "CTRLR: Build Win32"
-		echo $DOTNET/MSBuild.exe $CTRLR_ROOT/Builds/Ctrlr_Release.sln /fileloggerparameters:logfile=Ctrlr-$VERSION.win32.build.log /property:Configuration=Release_Nightly /property:Platform=Win32 /maxcpucount:6
-		if [ $? -ne 0 ]; then
-			echo "CTRLR: Win32 build failed"
-			exit 1
-		fi
-		echo "CTRLR: Build x64"
-		echo $DOTNET/MSBuild.exe $CTRLR_ROOT/Builds/Ctrlr_Release.sln /fileloggerparameters:logfile=Ctrlr-$VERSION.win64.build.log /property:Configuration=Release_Nightly /property:Platform=x64 /maxcpucount:6
-		if [ $? -ne 0 ]; then
-			echo "CTRLR: x64 build failed"
-			exit 1
-		fi
-		
-		echo "CTRLR: Build success, create installer"
-		eval $NSIS $CTRLR_ROOT/Packaging/Windows/ctrlr.nsi
-		if [ $? -ne 0 ]; then
-			echo "CTRLR: failed to create installer package"
-			exit 1
-		fi
-		echo "CTRLR: rename $CTRLR_ROOT/Packaging/Windows/Ctrlr.exe -> $PACKAGE"
-		mv $CTRLR_ROOT/Packaging/Windows/Ctrlr.exe $PACKAGE
-		if [ $? -ne 0 ]; then
-			echo "CTRLR: failed to rename installer package"
-			exit 1
-		fi
-		scp -v -i $CTRLR_ROOT/Packaging/ctrlr.key $PACKAGE $BUILD_LOG_WIN32 $BUILD_LOG_WIN64 $OUTPUT
-		if [ $? -ne 0 ]; then
-			echo "CTRLR: failed to transfer package files to remote site"
-			exit 1
-		fi
+	if [ "$ARGS" != "package" ]; then
+		windows_msbuild
+	fi
+	
+	echo "CTRLR: Build success, create installer"
+	eval $NSIS $CTRLR_ROOT/Packaging/Windows/ctrlr.nsi
+	if [ $? -ne 0 ]; then
+		echo "CTRLR: failed to create installer package"
+		exit 1
+	fi
+	
+	echo "CTRLR: rename $CTRLR_ROOT/Packaging/Windows/Ctrlr.exe -> $PACKAGE"
+	mv $CTRLR_ROOT/Packaging/Windows/Ctrlr.exe $PACKAGE
+	if [ $? -ne 0 ]; then
+		echo "CTRLR: failed to rename installer package"
+		exit 1
+	fi
+	scp -v -i  $CTRLR_KEY $PACKAGE $BUILD_LOG_WIN32 $BUILD_LOG_WIN64 $OUTPUT
+	if [ $? -ne 0 ]; then
+		echo "CTRLR: failed to transfer package files to remote site"
+		exit 1
 	fi
 }
 
